### ISSUE TITLE
SetHeader "Authorization" ignored if set on the Client

### ISSUE THREAD

**Issue by OJFord** [go-resty/resty#316] opened 2020-02-29 18:52 UTC
```go
client.SetHeader("Authorization", "foo")
```

is ignored/overwritten; it must instead be add in `client.OnBeforeRequest` handler.

**Comment by jeevatkm** [comment] 2020-03-02 02:49
@OJFord Thanks for reaching out. I'm unable to fully understand your issue in nature. Just taking an appropriate guess.

Please check this test case `TestRequestOverridesClientAuthorizationHeader` and play around with it then let me know.

**Comment by OJFord** [comment] 2020-03-02 10:23
@jeevatkm Sorry that wasn't very clear.

That test does:
```go
	c.SetTLSClientConfig(&tls.Config{InsecureSkipVerify: true}).
		SetHeader("Authorization", "some token").
		SetHostURL(ts.URL + "/")

	resp, err := c.R().
		SetHeader("Authorization", "Bearer 004DDB79-6801-4587-B976-F093E6AC44FF").
		Get("/profile")
```

The issue I'm seeing is that if the second `SetHeader` - the one on the request - isn't there, the Authorization header is _not_ set to `some token` - the call on the client (rather than request) seems to be ignored.

As a workaround, what I've done to set it on each request is set it in the function passed to `OnBeforeRequest`:
```go
	c.OnBeforeRequest(func(/*...*/) {
		r.SetHeader("Authorization", "foo")
	})
```

which isn't as succinct but of course has the same behaviour as expected from `c.SetHeader("Authorization", "foo")`.

**Comment by jeevatkm** [comment] 2020-03-03 04:57
@OJFord I think I did not explain it properly. The reason I have shared that test case for you play around with it. Example, in the test case `TestRequestOverridesClientAuthorizationHeader` if you comment out the line
```go
SetHeader("Authorization", "Bearer 004DDB79-6801-4587-B976-F093E6AC44FF").
```

then you will get an unauthorized 401 error (like the log below).  Since it sends the header that was set on the client. Then uncomment the line and run it again you will get success.

----

```
$ go test -run ^TestRequestOverridesClientAuthorizationHeader$
2020/03/02 20:51:14.533715 DEBUG RESTY
==============================================================================
~~~ REQUEST ~~~
GET  /profile  HTTP/1.1
HOST   : 127.0.0.1:64792
HEADERS:
	Authorization: some token
	User-Agent: go-resty/2.3.0-dev (https://github.com/go-resty/resty)
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 401 Unauthorized
RECEIVED AT  : 2020-03-02T20:51:14.533191-08:00
TIME DURATION: 6.369726ms
HEADERS      :
	Content-Length: 58
	Content-Type: application/json; charset=utf-8
	Date: Tue, 03 Mar 2020 04:51:14 GMT
	Www-Authenticate: Protected Realm
BODY         :
{
   "id": "unauthorized",
   "message": "Invalid credentials"
}
==============================================================================
--- FAIL: TestRequestOverridesClientAuthorizationHeader (0.01s)
    resty_test.go:394: Method: GET
    resty_test.go:395: Path: /profile
    resty_test.go:396: Content-Type:
    resty_test.go:402: Bearer Auth: some token
    resty_test.go:602: Expected [200], got [401]
FAIL
coverage: 23.2% of statements
exit status 1
FAIL	github.com/go-resty/resty/v2	0.112s
$
```

**Comment by moorereason** [comment] 2020-03-03 15:21
I modified the test to match @OJFord's case, and I works as expected (see below).  @OJFord, can you provide a test case that fails the way you're describing?

```diff
diff --git a/request_test.go b/request_test.go
index 745ac37..9ecfc0c 100644
--- a/request_test.go
+++ b/request_test.go
@@ -1451,11 +1450,10 @@ func TestRequestOverridesClientAuthorizationHeader(t *testing.T) {

        c := dc()
        c.SetTLSClientConfig(&tls.Config{InsecureSkipVerify: true}).
-               SetHeader("Authorization", "some token").
+               SetHeader("Authorization", "Bearer 004DDB79-6801-4587-B976-F093E6AC44FF").
                SetHostURL(ts.URL + "/")

        resp, err := c.R().
-               SetHeader("Authorization", "Bearer 004DDB79-6801-4587-B976-F093E6AC44FF").
                Get("/profile")

        assertError(t, err)
```

```
$ go test -run=OverridesClientAuth -v
=== RUN   TestRequestOverridesClientAuthorizationHeader
    TestRequestOverridesClientAuthorizationHeader: resty_test.go:394: Method: GET
    TestRequestOverridesClientAuthorizationHeader: resty_test.go:395: Path: /profile
    TestRequestOverridesClientAuthorizationHeader: resty_test.go:396: Content-Type:
    TestRequestOverridesClientAuthorizationHeader: resty_test.go:402: Bearer Auth: Bearer 004DDB79-6801-4587-B976-F093E6AC44FF
--- PASS: TestRequestOverridesClientAuthorizationHeader (0.00s)
PASS
ok      github.com/go-resty/resty/v2    0.006s
```

**Comment by OJFord** [comment] 2020-03-04 19:32
Sure, here:
```patch
diff --git request_test.go request_test.go
index 745ac37..6973321 100644
--- request_test.go
+++ request_test.go
@@ -1675,3 +1675,16 @@ func TestDebugLoggerRequestBodyTooLarge(t *testing.T) {
 	assertNotNil(t, resp)
 	assertEqual(t, true, strings.Contains(output.String(), "REQUEST TOO LARGE"))
 }
+
+func Test316(t *testing.T) {
+	c := dc()
+	type HeadersResponse struct {
+		headers map[string]string
+	}
+
+	c.SetHeader("Authorization", "some token")
+	resp, err := c.R().SetResult(HeadersResponse{}).Get("https://httpbin.org/headers")
+
+	assertError(t, err)
+	assertEqual(t, "some token", resp.Result().(*HeadersResponse).headers["Authorization"])
+}
```


> --- FAIL: Test316 (0.32s)
>    resty_test.go:602: Expected [some token], got []

**Comment by OJFord** [comment] 2020-03-04 19:33
(By the way, sorry if my Go's weird - I don't use it much.)

**Comment by moorereason** [comment] 2020-03-05 13:45
@OJFord,
I'm confused.  You're test is checking for an `Authorization` header in the *response*, not the request.

**Comment by OJFord** [comment] 2020-03-06 14:22
@moorereason https://httpbin.org/headers returns the request headers in the response body under key `"headers"`.

**Comment by moorereason** [comment] 2020-03-06 16:36
Oh, my bad.  I don't use httpbin.org much.

If you print the response body in your test, you'll see that the `Authorization` header is present.  The issue there has to do with `SetResult` not working as expected.

**Comment by jeevatkm** [comment] 2020-05-11 07:07
@OJFord Thanks for providing a test case. That cleared up all my questions.

So you have an incorrect field definition for JSON on headers. **Go JSON will only work for exported fields**.

I have updated your test case with correction, please find it below.

```go
func Test316(t *testing.T) {
	c := dc()
	type HeadersResponse struct {
		Headers map[string]string `json:"headers"`
	}

	c.SetHeader("Authorization", "some token")
	resp, err := c.R().SetResult(HeadersResponse{}).Get("https://httpbin.org/headers")

	assertError(t, err)
	assertEqual(t, "some token", resp.Result().(*HeadersResponse).Headers["Authorization"])
}
```

**Comment by jeevatkm** [comment] 2020-05-11 07:08
@moorereason FYI

I'm closing this issue. Thanks.

**Closed by jeevatkm** 2020-05-11 07:08 UTC
Labels: answered, support, v2

**Comment by OJFord** [comment] 2020-05-13 14:40
@jeevatkm Ok, but that's a bug with the test I wrote right? It's not actually anything to do with the issue I initially reported, it's just how I (tried to) reproduced it?

**Comment by moorereason** [comment] 2020-05-13 15:16
@OJFord,
We're unable to reproduce your original report ([here](https://github.com/go-resty/resty/issues/316#issuecomment-593767912) and [here](https://github.com/go-resty/resty/issues/316#issuecomment-594006011)...and even [here](https://github.com/go-resty/resty/issues/316#issuecomment-626513928)).

We can only assume this issue is resolved unless you can provide a simple example that clearly demonstrates the problem.
