### ISSUE TITLE
`trace.dnsStart` will be zero if client was reused and transport got persistConn from idle queue

### ISSUE THREAD

**Issue by clannadxr** [go-resty/resty#396] opened 2020-12-07 17:35 UTC
`clientTrace.dnsStart` and `clientTrace.dnsDone` will be set when `DNSStart`/ `DNSDone` or `ConnectStart` hook be called.

When `resty.Client` was reused and the transport delivered an already-idle connection, those hooks above won't be called thus leading to `clientTrace.dnsStart` and `clientTrace.dnsDone` be zero

**Comment by moorereason** [comment] 2020-12-07 23:55
Isn't that by design since no new connection is established?  What would you expect them to be if not zero?  On a connection re-use scenario, several hooks are skipped (DNSStart, DNSDone, ConnectStart, ConnectDone, TLSHandshakeStart, & TLSHandshakeDone).

**Comment by clannadxr** [comment] 2020-12-08 00:37
@moorereason sorry, the actual issue was `response.Time()` is calculated by `clientTrace.endTime.Sub(clientTrace.dnsStart)` when trace is enabled. So if when `dnsStart` is zero, `response.Time()` would be maximum duration.

**Comment by moorereason** [comment] 2020-12-08 15:59
Are you using the latest resty?  This issue should be resolved in v2.4.0 (see #347).

**Comment by clannadxr** [comment] 2020-12-08 16:22
@moorereason Oh sorry didn't check the latest codes. 

I noticed the v2.4.0 has not released yet, since it's a bug could you please merge it into v2.3.x and release a minor version if v2.4.0 is not ready for now

**Comment by moorereason** [comment] 2020-12-08 16:26
My bad.  I forgot that v2.4.0 isn't released yet.

Cc: @jeevatkm

**Comment by git-hulk** [comment] 2020-12-31 04:02
hi, @moorereason when the v2.4.0 would be released, we are suffering from this issue as well.

:) thanks

**Comment by jeevatkm** [comment] 2021-01-10 13:56
@git-hulk @clannadxr I'm sorry will do the release in few days. 

@moorereason Thanks.

**Comment by jeevatkm** [comment] 2021-01-11 22:58
@git-hulk @clannadxr v2.4.0 is released, can you try and let us know?

**Comment by git-hulk** [comment] 2021-01-12 01:04
> @git-hulk @clannadxr v2.4.0 is released, can you try and let us know?

Thanks for your great work, I will try it out later.

**Closed** 2021-02-15 09:31 UTC
