### ISSUE TITLE
Hope the function SetFormData support map[string]interface{}

### ISSUE THREAD

**Issue by yunduan16** [go-resty/resty#550] opened 2022-06-20 08:38 UTC
The function SetFormData now only support the type of map[string]string, but sometimes we need the input param type is 
map[string]interface{}.Hopefully, this type will be supported soon. Thank you! 🙏 😊

**Comment by moorereason** [comment] 2022-06-21 23:24
Duplicate of #265.  You need to do the conversion yourself.

**Closed** 2022-06-21 23:25 UTC
