### ISSUE TITLE
Limit the maximum number of requests

### ISSUE THREAD

**Issue by liyuan1125** [go-resty/resty#468] opened 2021-10-01 03:06 UTC
For example, how to limit the maximum number of requests during concurrent requests?

**Comment by lavoiesl** [comment] 2021-10-29 18:04
Is this a duplicate of https://github.com/go-resty/resty/issues/256?

**Comment by leewithyuan** [comment] 2021-10-30 15:12
> @leewithyuan I'm sorry, I didn't get it. Do you mean throttling?

Sorry, I have solved it, the maximum number of requests is limited to 100;

```go
      var reqChan = make(chan time.Time, 100)

	cli := resty.New()

	cli.OnBeforeRequest(func(client *resty.Client, request *resty.Request) error {
		reqChan <- request.Time
		return nil
	})

	cli.OnAfterResponse(func(client *resty.Client, response *resty.Response) error {
		<-reqChan
		return nil
	})
```

**Comment by tylerstillwater** [comment] 2022-01-30 01:50
I believe the correct way to do this is construct a new `http.Transport` and give it a `MaxConnsPerHost`.

Something like this:

```dialer := &net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
	}
	restyClient.SetTransport(&http.Transport{
		Proxy:                 http.ProxyFromEnvironment,
		DialContext:           dialer.DialContext,
		ForceAttemptHTTP2:     true,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
		MaxIdleConnsPerHost:   runtime.GOMAXPROCS(0) + 1,
		MaxConnsPerHost: 100,
	})```

**Comment by jeevatkm** [comment] 2024-10-04 06:08
The upcoming Resty v3 provides an easy way to control/override selected settings as required. Currently, it is available on the `main` branch.

https://github.com/go-resty/resty/blob/0d0bc1b1d873414d17ca6fb4e5240165672dd022/resty.go#L31

Examples:
```go
client1 := resty.NewWithTransportSettings(&resty.TransportSettings{
	MaxConnsPerHost: 100,
})
```

```go
client2 := resty.NewWithTransportSettings(&resty.TransportSettings{
	MaxIdleConns:    50,
	MaxConnsPerHost: 100,
})
```

**Closed by jeevatkm** 2024-10-04 06:08 UTC
Labels: v3-docs
