### ISSUE TITLE
Path parameter specified using client.SetBaseURL doesn't get replaced by its value 

### ISSUE THREAD

**Issue by bambulin** [go-resty/resty#898] opened 2024-10-31 10:47 UTC
We need to consume an API where part of URL is parameter that specifies a context for the API.

the schema is similar to this:
```
http://api.domain.com:port/static-part/{context-parameter}/static-part2/static-part3/<endpoint-path>
```

we expect to initiate the client using:
```
resty.New().SetBaseURL(`http://api.domain.com:port/static-part/{context-parameter}/static-part2/static-part3`)
```

and then using `request.SetPathParam("context-parameter", "value").Get("/endpointX")` create a request that reaches server on path `http://api.domain.com:port/static-part/value/static-part2/static-part3/endpointX`

However if the path param is defined using base url it remains unaffected and the placeholder doesn't get replaced by its value. It doesn't make much sense to have ability to set path param values on client level using `resty.New().SetPathParam` but then require to specify the path param placeholder for each endpoint again on request lvl using `client.R().Get("/{path-param}/something")` `client.R().Post("/{path-param}/something-else")` etc...

example:
```
func TestClientPathParam(t *testing.T) {
	srv := httptest.NewServer(
		http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
			fmt.Printf("%s\n", req.URL.Path)
		}),
	)
	defer srv.Close()

	// path parameter in BaseURL
	client1 := resty.New().SetBaseURL(srv.URL + "/{base-path-param}/static/part")
	req1 := client1.NewRequest().SetPathParam("base-path-param", "value")

	resp1, err := req1.Get("/endpoint")
	assert.NoError(t, err)
	assert.True(t, resp1.IsSuccess())

	// path parameter in request URL
	client2 := resty.New().SetBaseURL(srv.URL)
	req2 := client2.NewRequest().SetPathParam("req-path-param", "value")

	resp2, err := req2.Get("/{req-path-param}/static/part/endpoint")
	assert.NoError(t, err)
	assert.True(t, resp2.IsSuccess())
}

output: 
/{base-path-param}/static/part/endpoint
/value/static/part/endpoint
```

Expected behaviour:

path parameters defined by SetBaseURL get replaced by their values the same way as they were defined by `request.Get()`, `request.Post()` etc.

**Comment by jeevatkm** [comment] 2024-10-31 19:56
@bambulin Thanks for reaching out.

By design, Resty does not manipulate the path variable on the Base URL; it only does so for the request path. Base URL values are usually something like `http://api.domain.com:port`. FYI, in the upcoming Resty v3, the Base URL plays a good role in users' ability to [balance client-side load](https://github.com/go-resty/resty/commit/55860ab8e6a31c982b50ea686e8847a40d3eb02f) if required.

The feature option provided at the client instance level is to take advantage of common/repeated values on each request. So that users are not required to add that to every request. 

Typically, creating a Resty client per host/base URL and preparing that client with all the required settings and values is recommended. Then, override those settings or values at the request level as needed for the particular request.

I hope it clarifies the purpose.

Something like this -
```go
func TestSample(t *testing.T) {
	srv := httptest.NewServer(
		http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
			fmt.Printf("The Request Path: %s\n", req.URL.Path)
		}),
	)
	defer srv.Close()

	client := resty.New().
		SetBaseURL(srv.URL).
		SetPathParam("req-path-param", "client-value")

	resp1, err1 := client.R(). // we do not need to add value that is already added at the client level
		Get("/{req-path-param}/static/part/endpoint")
	fmt.Println(err1, resp1)

	resp2, err2 := client.R().
		SetPathParam("req-path-param", "request-value"). // override
		Get("/{req-path-param}/static/part/endpoint")
	fmt.Println(err2, resp2)
}
```
Output:
```
The Request Path: /client-value/static/part/endpoint
<nil> 
The Request Path: /request-value/static/part/endpoint
<nil> 
```

**Comment by jeevatkm** [comment] 2024-11-12 06:27
I'm closing it.

**Closed by jeevatkm** 2024-11-12 06:27 UTC
Labels: answered
